### PR TITLE
Add Time.ToString

### PR DESCRIPTION
**Pull request by Kryptos-FR**
Convert time to a human readable string.

**Examples**
```clj
0 (Time.ToString) (Log) ; 0s
59 (Time.ToString) (Log) ; 59s
60 (Time.ToString) (Log) ; 1m:0s
61 (Time.ToString) (Log) ; 1m:1s
(Time.EpochMs) (Time.ToString :Millis true) (Log) ; 53y:84d:13h:26m:28s
```

### CODE REVIEW

**Review by sinkingsugar — APPROVED** [review]
Ok for now but formatting should be customizable eventually 👍
Easy to add as extra param in the future.

**Comment by sinkingsugar** [comment]
add test for coverage to CI

**Comment by sinkingsugar** [comment]
nm docs are covered?

**Comment by Kryptos-FR** [comment]
> nm docs are covered?

Yes they are:
- https://github.com/fragcolor-xyz/shards/blob/devel/.github/workflows/build-linux.yml#L146
- https://github.com/fragcolor-xyz/shards/blob/devel/.github/workflows/build-linux.yml#L146

**Pull request merged**
