### PR TITLE
Create the Fragnova Testnet help document

### PR DESCRIPTION
**Pull request by satendrapalsingh**

### CODE REVIEW

**Comment by sinkingsugar** [comment]
Why this is on shards repo?
We already had this conversation... please...

**Comment by satendrapalsingh** [comment]
> Why this is on shards repo? We already had this conversation... please... Move to clamor, we need to publish from there too...

Sorry, some confusion - I don't remember that discussion about this to be hosted from Clamor.
I'll move the assets and markdown file to Clamor repo (/clamor/docs) but will still need to host this file somewhere. We decided to just include a link to this doc on the markeplace/help.

@paulinechi FYI

**Comment by Kryptos-FR** [comment]
> we need to publish from there too...

 Where do we want to publish it? And in what form? AFAIK GitHub pages can't combine documents from several repos. There would be several GitHub Pages websites.

**Comment by satendrapalsingh** [comment]
@Kryptos-FR Gio has suggested that for now we move this to a word doc and then publish it as a medium article.
I've created the doc [here](https://docs.google.com/document/d/10BaRab6eM9UmpVBoJqFsH4xhLj9VuWHmp7ZglZxShAQ/edit#), but I'll wait for our discussion in the tech team meeting before I close/abandon this PR.

**Comment by satendrapalsingh** [comment]
PR not needed

**Pull request closed without merging**
