### PR TITLE
Factor out branch implementation

### PR DESCRIPTION
**Pull request by guusw**
I required very similar implementation for the GFX.Feature generators, so I'm factoring out the implementation into some shared code

### CODE REVIEW

**Review by sinkingsugar — APPROVED** [review]

**Review by Kryptos-FR — APPROVED** [review]

**Comment by sinkingsugar** [comment]
Don't merge yet, says @guusw :D

**Comment by sinkingsugar** [comment]
@guusw merge if you done and tests pass

**Comment by sinkingsugar** [comment]
Weird early failure. Params seems messed.

**Comment by guusw** [comment]
Fixed the params, Brancher could have null Mesh. Okay to merge now @sinkingsugar  ?

**Pull request merged**
