### PR TITLE
Rust build macros

### LINKED ISSUE #275: Wrap reusable rust build code in CMake macros/functions
Currently some rust build code is copy/pasted across shards/wgpu-native.
Check: [rust\CMakeLists.txt](https://github.com/fragcolor-xyz/shards/blob/3f1f9141d6400d3aaf907db7b9945f1016a288d3/rust/CMakeLists.txt#L51), [src\gfx\CMakeLists.txt](https://github.com/fragcolor-xyz/shards/blob/3f1f9141d6400d3aaf907db7b9945f1016a288d3/src/gfx/CMakeLists.txt#L116)
We need some functions that define an external rust target that is built so we can easlily add new once

### PR DESCRIPTION
**Pull request by guusw**
Refactors usages for custom commands for rust build in CMake into a reusable macro.
This make it easier to add/split libraries

Also renamed some of the variables from Rust_* to RUST_* for consistency

This closes #275

### CODE REVIEW

**Comment by Kryptos-FR** [comment]
Just FYI, this PR and related issue wasn't scheduled for the current sprint. Since it is not critical it should have been kept for later. We have `egui` backend as a higher priority.

**Review by sinkingsugar — APPROVED** [review]
🙏👍

**Review by Kryptos-FR — COMMENTED** [review]
Are the changes in `shards.rs` and `context.hpp` related to this PR?

**Comment by guusw** [comment]
Not really, just some minor adjustments / removing unused code.

**Review by Kryptos-FR — APPROVED** [review]

**Pull request merged**
