### PR TITLE
Track only a single exposed/required type per name

### PR DESCRIPTION
**Pull request by guusw**
- Fixup table types in Set.
- Return existing table type in Update.

Main thing this does is support the test cases in the added table-compose.edn:
```edn
{:a 0 :b 1 :c 2} >= .table
.table (Do wire-1)

; This should update b in the table
4 (Update .table :Key "b")
.table (Do wire-1)

5 (Set .table :Key "d")
.table (Do wire-2)
```

### CODE REVIEW

**Comment by guusw** [comment]
TODO: Check if we still need isPushTable, since we have stable maps now.

**Review by sinkingsugar — COMMENTED** [review]
Looks good I hope it works smoothly, for some reasons this is something I never wanted to touch!

**Comment by sinkingsugar** [comment]
@guusw add coverage and possibly less coverage means some silent failure too! check logs

**Comment by guusw** [comment]
Merged in devel ee544f4426b761c0782bafb84594f4cd29da8cd4

**Pull request closed without merging**
